/**
 * agents-hub CLI
 *
 * Commands:
 *   init    Create a new project
 *   dev     Start development server
 *   build   Build for production
 *   deploy  Build and deploy to Cloudflare
 */

import { spawn } from "node:child_process";
import * as fs from "node:fs";
import * as path from "node:path";
import { fileURLToPath } from "node:url";

// Read version from package.json at runtime
function getVersion(): string {
  try {
    const __dirname = path.dirname(fileURLToPath(import.meta.url));
    // Go up from dist/cli to package root (dist/cli -> dist -> package root)
    const pkgPath = path.resolve(__dirname, "..", "..", "package.json");
    const pkg = JSON.parse(fs.readFileSync(pkgPath, "utf-8"));
    return pkg.version;
  } catch {
    return "0.0.0";
  }
}

const VERSION = getVersion();

const HELP = `
agents-hub v${VERSION}

Usage: agents-hub <command> [options]

Commands:
  init <name>  Create a new agents-hub project
  dev          Start development server
  build        Build for production
  deploy       Build and deploy to Cloudflare

Options:
  --help, -h     Show help
  --version, -v  Show version

Init options:
  --no-install   Skip npm install

Dev options:
  --port <port>  Server port (default: 5173)
  --host         Expose to network

Build options:
  --outDir <dir>  Output directory

Deploy options:
  --env <name>    Wrangler environment
  --dry-run       Show what would be deployed

Examples:
  npx agents-hub init my-hub
  npx agents-hub dev
  npx agents-hub dev --port 4000
  npx agents-hub build
  npx agents-hub deploy
  npx agents-hub deploy --env staging
`;

function parseArgs(args: string[]): {
  command: string;
  flags: Record<string, string | boolean>;
  rest: string[];
} {
  const flags: Record<string, string | boolean> = {};
  const positional: string[] = [];

  for (let i = 0; i < args.length; i++) {
    const arg = args[i];
    if (arg.startsWith("--")) {
      const key = arg.slice(2);
      const next = args[i + 1];
      if (next && !next.startsWith("-")) {
        flags[key] = next;
        i++;
      } else {
        flags[key] = true;
      }
    } else if (arg.startsWith("-")) {
      const key = arg.slice(1);
      flags[key] = true;
    } else {
      positional.push(arg);
    }
  }

  const [command = "help", ...rest] = positional;
  return { command, flags, rest };
}

function findProjectRoot(): string {
  let dir = process.cwd();
  while (dir !== path.dirname(dir)) {
    if (fs.existsSync(path.join(dir, "package.json"))) {
      return dir;
    }
    dir = path.dirname(dir);
  }
  return process.cwd();
}

function findHubDir(root: string): string | null {
  const candidates = ["hub", "src/hub", "agents"];
  for (const candidate of candidates) {
    const fullPath = path.join(root, candidate);
    if (fs.existsSync(fullPath) && fs.statSync(fullPath).isDirectory()) {
      return fullPath;
    }
  }
  return null;
}

function hasViteConfig(root: string): boolean {
  const configs = [
    "vite.config.ts",
    "vite.config.js",
    "vite.config.mts",
    "vite.config.mjs",
  ];
  return configs.some((c) => fs.existsSync(path.join(root, c)));
}

/**
 * Generate a temporary vite config for zero-config mode
 */
function generateTempConfig(root: string, hubDir: string): string {
  const configPath = path.join(root, ".agents-hub.vite.config.ts");
  const relativeSrc = path.relative(root, hubDir);

  const config = `
// Auto-generated by agents-hub CLI - do not edit
import { defineConfig } from "vite";
import hub from "agents-hub/vite";

export default defineConfig({
  plugins: [
    hub({
      srcDir: "./${relativeSrc}",
    }),
  ],
  server: {
    cors: true, // Allow cross-origin requests in dev mode
  },
});
`;

  fs.writeFileSync(configPath, config);
  return configPath;
}

function cleanupTempConfig(configPath: string): void {
  try {
    if (fs.existsSync(configPath)) {
      fs.unlinkSync(configPath);
    }
  } catch {
    // Ignore cleanup errors
  }
}

async function runVite(
  command: "dev" | "build",
  flags: Record<string, string | boolean>
): Promise<void> {
  const root = findProjectRoot();
  const hasConfig = hasViteConfig(root);
  let tempConfig: string | null = null;

  if (!hasConfig) {
    const hubDir = findHubDir(root);
    if (!hubDir) {
      console.error(
        "Error: No hub directory found. Create a 'hub/' folder with your agents, tools, and plugins."
      );
      console.error(
        "Alternatively, create a vite.config.ts with the agents-hub plugin."
      );
      process.exit(1);
    }
    tempConfig = generateTempConfig(root, hubDir);
    console.log(`[agents-hub] Using zero-config mode with ${path.relative(root, hubDir)}/`);
  }

  const viteArgs: string[] = [command];

  // Pass through flags
  if (flags.port) viteArgs.push("--port", String(flags.port));
  if (flags.host) viteArgs.push("--host");
  if (flags.outDir) viteArgs.push("--outDir", String(flags.outDir));
  if (tempConfig) viteArgs.push("--config", tempConfig);

  // Try to find vite binary
  const vite = resolveViteBin(root);
  if (!vite) {
    console.error("Error: vite not found. Install it with: npm install vite");
    if (tempConfig) cleanupTempConfig(tempConfig);
    process.exit(1);
  }

  const child = spawn(vite.bin, [...vite.args, ...viteArgs], {
    cwd: root,
    stdio: "inherit",
    shell: process.platform === "win32",
  });

  // Cleanup temp config on exit
  const cleanup = () => {
    if (tempConfig) cleanupTempConfig(tempConfig);
  };

  process.on("SIGINT", cleanup);
  process.on("SIGTERM", cleanup);

  child.on("exit", (code) => {
    cleanup();
    process.exit(code ?? 0);
  });

  child.on("error", (err) => {
    console.error("Failed to start vite:", err.message);
    cleanup();
    process.exit(1);
  });
}

async function runDeploy(flags: Record<string, string | boolean>): Promise<void> {
  const root = findProjectRoot();

  // First, run build
  console.log("[agents-hub] Building for production...\n");

  const buildFlags = { ...flags };
  delete buildFlags.env;
  delete buildFlags["dry-run"];

  await new Promise<void>((resolve, reject) => {
    const hasConfig = hasViteConfig(root);
    let tempConfig: string | null = null;

    if (!hasConfig) {
      const hubDir = findHubDir(root);
      if (!hubDir) {
        console.error("Error: No hub directory found.");
        process.exit(1);
      }
      tempConfig = generateTempConfig(root, hubDir);
    }

    const viteArgs = ["build"];
    if (tempConfig) viteArgs.push("--config", tempConfig);

    const vite = resolveViteBin(root);
    if (!vite) {
      console.error("Error: vite not found.");
      if (tempConfig) cleanupTempConfig(tempConfig);
      process.exit(1);
    }

    const child = spawn(vite.bin, [...vite.args, ...viteArgs], {
      cwd: root,
      stdio: "inherit",
      shell: process.platform === "win32",
    });

    child.on("exit", (code: number | null) => {
      if (tempConfig) cleanupTempConfig(tempConfig);
      if (code === 0) resolve();
      else reject(new Error(`Build failed with code ${code}`));
    });

    child.on("error", (err: Error) => {
      if (tempConfig) cleanupTempConfig(tempConfig);
      reject(err);
    });
  });

  // Then, run wrangler deploy
  console.log("\n[agents-hub] Deploying to Cloudflare...\n");

  const wranglerArgs = ["wrangler", "deploy"];
  if (flags.env) wranglerArgs.push("--env", String(flags.env));
  if (flags["dry-run"]) wranglerArgs.push("--dry-run");

  const child = spawn("npx", wranglerArgs, {
    cwd: root,
    stdio: "inherit",
    shell: process.platform === "win32",
  });

  child.on("exit", (code) => {
    process.exit(code ?? 0);
  });

  child.on("error", (err) => {
    console.error("Failed to run wrangler:", err.message);
    console.error("Make sure wrangler is installed: npm install -D wrangler");
    process.exit(1);
  });
}

// ============================================================
// Init Command
// ============================================================

const PACKAGE_JSON_TEMPLATE = (name: string) => `{
  "name": "${name}",
  "version": "0.0.1",
  "type": "module",
  "private": true,
  "scripts": {
    "dev": "agents-hub dev",
    "build": "agents-hub build",
    "deploy": "agents-hub deploy"
  },
  "dependencies": {
    "agents-hub": "^${VERSION}"
  }
}
`;

const AGENT_TEMPLATE = `import type { AgentBlueprint } from "agents-hub";

export default {
  name: "assistant",
  description: "A helpful assistant",
  prompt: \`You are a helpful assistant. Be concise and friendly.

When asked to perform tasks, use the available tools to help the user.
Always explain what you're doing and report the results clearly.\`,
  capabilities: ["@default"],
  model: "gpt-4o",
} satisfies AgentBlueprint;
`;

const TOOL_TEMPLATE = `import { tool } from "agents-hub";
import { z } from "zod";

export const greetTool = tool({
  name: "greet",
  description: "Greet a user by name",
  inputSchema: z.object({
    name: z.string().describe("The name to greet"),
  }),
  execute: async ({ name }) => {
    return \`Hello, \${name}! Welcome to agents-hub.\`;
  },
});
`;

const DEV_VARS_TEMPLATE = `# LLM Provider Configuration
# Get your API key from https://platform.openai.com/api-keys
LLM_API_KEY=sk-your-api-key-here
LLM_API_BASE=https://api.openai.com/v1

# Optional: API authentication secret
# SECRET=your-secret-here
`;

const GITIGNORE_TEMPLATE = `node_modules/
dist/
.dev.vars
_generated.ts
.agents-hub.vite.config.ts
.wrangler/
`;

async function runInit(
  projectName: string,
  flags: Record<string, string | boolean>
): Promise<void> {
  const targetDir = path.resolve(process.cwd(), projectName);

  // Check if directory exists
  if (fs.existsSync(targetDir)) {
    const files = fs.readdirSync(targetDir);
    if (files.length > 0) {
      console.error(`Error: Directory '${projectName}' already exists and is not empty.`);
      process.exit(1);
    }
  }

  console.log(`\nCreating a new agents-hub project in ${targetDir}\n`);

  // Create directory structure
  fs.mkdirSync(targetDir, { recursive: true });
  fs.mkdirSync(path.join(targetDir, "hub", "agents"), { recursive: true });
  fs.mkdirSync(path.join(targetDir, "hub", "tools"), { recursive: true });
  fs.mkdirSync(path.join(targetDir, "hub", "plugins"), { recursive: true });

  // Write files
  fs.writeFileSync(
    path.join(targetDir, "package.json"),
    PACKAGE_JSON_TEMPLATE(projectName)
  );
  fs.writeFileSync(
    path.join(targetDir, "hub", "agents", "assistant.ts"),
    AGENT_TEMPLATE
  );
  fs.writeFileSync(
    path.join(targetDir, "hub", "tools", "greet.ts"),
    TOOL_TEMPLATE
  );
  fs.writeFileSync(
    path.join(targetDir, ".dev.vars"),
    DEV_VARS_TEMPLATE
  );
  fs.writeFileSync(
    path.join(targetDir, ".gitignore"),
    GITIGNORE_TEMPLATE
  );

  console.log("  Created package.json");
  console.log("  Created hub/agents/assistant.ts");
  console.log("  Created hub/tools/greet.ts");
  console.log("  Created hub/plugins/");
  console.log("  Created .dev.vars");
  console.log("  Created .gitignore");

  // Run npm install unless --no-install flag
  if (!flags["no-install"]) {
    console.log("\nInstalling dependencies...\n");

    await new Promise<void>((resolve, reject) => {
      const child = spawn("npm", ["install"], {
        cwd: targetDir,
        stdio: "inherit",
        shell: process.platform === "win32",
      });

      child.on("exit", (code: number | null) => {
        if (code === 0) resolve();
        else reject(new Error(`npm install failed with code ${code}`));
      });

      child.on("error", (err: Error) => {
        reject(err);
      });
    });
  }

  console.log(`
Done! Your agents-hub project is ready.

Next steps:

  cd ${projectName}
  
  # Add your LLM API key
  # Edit .dev.vars and set LLM_API_KEY
  
  # Start development server
  npm run dev

  # Open http://localhost:5173 in your browser

Happy building!
`);
}

function resolveViteBin(root: string): { bin: string; args: string[] } | null {
  // Try local node_modules first
  const localBin = path.join(root, "node_modules", ".bin", "vite");
  if (fs.existsSync(localBin)) {
    return { bin: localBin, args: [] };
  }

  // Try windows variant
  const localBinCmd = localBin + ".cmd";
  if (process.platform === "win32" && fs.existsSync(localBinCmd)) {
    return { bin: localBinCmd, args: [] };
  }

  // Fallback to npx
  return { bin: "npx", args: ["vite"] };
}

async function main(): Promise<void> {
  const { command, flags } = parseArgs(process.argv.slice(2));

  // Handle help/version flags first (even without a command)
  if (flags.help || flags.h) {
    console.log(HELP);
    process.exit(0);
  }

  if (flags.version || flags.v) {
    console.log(`agents-hub v${VERSION}`);
    process.exit(0);
  }

  switch (command) {
    case "help":
      console.log(HELP);
      break;

    case "version":
      console.log(`agents-hub v${VERSION}`);
      break;

    case "init": {
      const { rest } = parseArgs(process.argv.slice(2));
      const projectName = rest[0];
      if (!projectName) {
        console.error("Error: Please provide a project name.");
        console.error("Usage: agents-hub init <project-name>");
        process.exit(1);
      }
      await runInit(projectName, flags);
      break;
    }

    case "dev":
      await runVite("dev", flags);
      break;

    case "build":
      await runVite("build", flags);
      break;

    case "deploy":
      await runDeploy(flags);
      break;

    default:
      console.error(`Unknown command: ${command}`);
      console.log(HELP);
      process.exit(1);
  }
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
